export const pokemonList = [
  { id: 1, name: "pikachu", image: "src/assets/pikachu.svg" },
  { id: 2, name: "bat", image: "src/assets/bat.svg" },
  { id: 3, name: "bulbasaur", image: "src/assets/bulbasaur.svg" },
  { id: 4, name: "charmander", image: "src/assets/charmander.svg" },
  { id: 5, name: "clown", image: "src/assets/clown.svg" },
  { id: 6, name: "crab", image: "src/assets/crab.svg" },
  { id: 7, name: "duck", image: "src/assets/duck.svg" },
  { id: 8, name: "electric-cat", image: "src/assets/electric-cat.svg" },
  { id: 9, name: "fire-back", image: "src/assets/fire-back.svg" },
  { id: 10, name: "fire-horse", image: "src/assets/fire-horse.svg" },
  { id: 11, name: "fox", image: "src/assets/fox.svg" },
  { id: 12, name: "hedgehog", image: "src/assets/hedgehog.svg" },
  { id: 13, name: "horse", image: "src/assets/horse.svg" },
  { id: 14, name: "hypnosis", image: "src/assets/hypnosis.svg" },
  { id: 15, name: "leaf", image: "src/assets/leaf.svg" },
  { id: 16, name: "long arm", image: "src/assets/long-arm.svg" },
  { id: 17, name: "meow", image: "src/assets/meow.svg" },
  { id: 18, name: "monkey", image: "src/assets/monkey.svg" },
  { id: 19, name: "muscles", image: "src/assets/muscles.svg" },
  { id: 20, name: "pink", image: "src/assets/pink.svg" },
  { id: 21, name: "plant", image: "src/assets/plant.svg" },
  { id: 22, name: "plato", image: "src/assets/plato.svg" },
  { id: 23, name: "purple", image: "src/assets/purple.svg" },
  { id: 24, name: "snake", image: "src/assets/snake.svg" },
  { id: 25, name: "squirtle", image: "src/assets/squirtle.svg" },
  { id: 26, name: "tadpole", image: "src/assets/tadpole.svg" },
  { id: 27, name: "tiger", image: "src/assets/tiger.svg" },
];
